In [1]:
import pickle
from dgllife.model.model_zoo import WeavePredictor
import dgl
import dgl.nn as nn
import dgl.function as fn
import torch.nn as tnn
import torch
import torch.optim
import torch.nn.functional as F
from torch.utils.data import random_split
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from pprint import pprint
from sklearn.preprocessing import MinMaxScaler

In [2]:
with open('graph_mean_ndatas.pickle', 'rb') as handle:
    ndatas = pickle.load(handle)

with open('graph_mean_edatas.pickle', 'rb') as handle:
    edatas = pickle.load(handle)
    
with open('graphs_mean.pickle', 'rb') as handle:
    graphs = pickle.load(handle)

In [3]:
def OHE_and_normalize(mol: str):
    n = []
    for i in range(graphs[mol].num_nodes()):
        for x in ndatas[mol]:
            if (x[0] == i):
                n.append(x[1:7]+[x[-1][0]])
                break
            elif (x[7] == i):
                n.append(x[8:14]+[x[-1][1]])
                break
    assert len(n) == graphs[mol].num_nodes()
    
    e = []
    for i, j in zip(graphs[mol].edges()[0].tolist(), graphs[mol].edges()[1].tolist()):
        for x in ndatas[mol]:
            if ((i, j) == (x[0], x[7])) or ((i, j) == (x[7], x[0])):
                e.append(x[-3:-1])
                break
        for y in edatas[mol].keys():
            if ((str(i), str(j)) == y) or ((str(j), str(i)) == y):
                e[-1].append(edatas[mol][y])
    assert len(e) == graphs[mol].num_edges()
            
    #n_df = pd.DataFrame(n)
    #encoded_column_1 = pd.get_dummies(n_df[0])
    #encoded_column_2 = pd.get_dummies(n_df[6], prefix="nei")
    #n_df = n_df.join(encoded_column_1)
    #n_df = n_df.join(encoded_column_2)
    #print(n_df)
    #df.drop(col, axis=1, inplace=True)
    # try:
    #df = df.join(encoded_column)
    # except ValueError as verr:
    #     if "overlap" in verr.__str__():
    #         df = df.merge(encoded_column, left_on="BR", right_on="BR")
    return n, e

In [4]:
sorted_keys = sorted([int(x) for x in ndatas.keys()])
n_all = []
e_all = []
for x in sorted_keys:
        x_n, x_e = OHE_and_normalize(str(x))
        n_all = n_all+x_n
        e_all = e_all+x_e

In [6]:
def save_obj_2_file(obj, fn):
    with open(fn, 'wb') as fh:
        pickle.dump(obj, fh)

In [5]:
n_df = pd.DataFrame(n_all, columns=["element", "atomic_number", "radius", "mass", "electronegativity", "hybridisation", "nei"])
e_df = pd.DataFrame(e_all)
ele_encoded = pd.get_dummies(n_df["element"], prefix="ele_")
nei_encoded = pd.get_dummies(n_df["nei"], prefix="nei")
n_df.drop("element", axis=1, inplace=True)
n_df.drop("nei", axis=1, inplace=True)
n_df = n_df.join(ele_encoded)
n_df = n_df.join(nei_encoded)
norm = MinMaxScaler().fit(n_df)
norm_n_df = norm.transform(n_df)

In [121]:
n_df.head()

,atomic_number,radius,mass,electronegativity,hybridisation,ele__B,ele__BR,ele__C,ele__CL,ele__F,...,nei_OP,nei_OS,nei_OSS,nei_P,nei_PP,nei_PS,nei_S,nei_SS,nei_SSS,nei_SSSS
0,6,70,12.00,2.55,4,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,6,70,12.00,2.55,4,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,6,70,12.00,2.55,4,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6,70,12.00,2.55,4,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1,25,1.01,2.20,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [101]:
graphs.keys()

dict_keys(['27024', '44986', '5541', '32535', '15373', '19079', '6041', '31551', '43442', '44773', '20136', '30421', '48765', '40868', '47654', '46378', '16415', '31931', '40325', '272749', '49748', '20359', '745', '38739', '29680', '20164', '33015', '43924', '38245', '48119', '41496', '7982', '38337', '4028', '47491', '47410', '48938', '113', '47243', '30203', '44886', '39278', '1938', '48876', '46390', '14506', '45729', '41678', '10060', '19043', '42115', '12031', '44552', '8026', '2418', '37232', '16813', '273068', '37950', '42275', '36468', '14291', '47823', '3743', '47398', '44660', '9753', '1923', '39700', '42798', '15419', '42998', '2126', '45308', '7984', '43942', '32090', '20662', '41054', '48972', '3811', '2666', '9719', '9367', '36341', '45298', '19012', '48258', '15952', '38291', '30210', '2112', '42340', '47221', '491', '1009', '35272', '1210', '9773', '41503', '273110', '46332', '3341', '30826', '39867', '31501', '11722', '39550', '14522', '44923', '49987', '272849', '44590', '37413', '10713', '41290', '45017', '37530', '48530', '47817', '23431', '6102', '49592', '101603', '30830', '41532', '38678', '39010', '41869', '30765', '42982', '4848', '37967', '43173', '11015', '12670', '33134', '24534', '14561', '274100', '32220', '47986', '45374', '47198', '10722', '460405', '6077', '15701', '14086', '10877', '1919', '37782', '31753', '32380', '40630', '25259', '10313', '39672', '37964', '37994', '35534', '45352', '44832', '41704', '48443', '272636', '12192', '39568', '10572', '21006', '9646', '20395', '45366', '38992', '47314', '22381', '42283', '21881', '1046', '49138', '3781', '40259', '37591', '37717', '33724', '43688', '29544', '11054', '22244', '35567', '12180', '2735', '263183', '39150', '39253', '38112', '9647', '10543', '39530', '12197', '28204', '9731', '4738', '40540', '31466', '42741', '29249', '49563', '2618', '45969', '17030', '19887', '21108', '39499', '40599', '3890', '34900', '39464', '46517', '38558', '43973', '11501', '41450', '32368', '26147', '273218', '38780', '41271', '32929', '42686', '47360', '32230', '19765', '38464', '4012', '272764', '30676', '3033', '12766', '43159', '5161', '16832', '2641', '48183', '3199', '40633', '42160', '40481', '30785', '42186', '30231', '1612180', '40713', '9918', '42676', '30372', '3328', '10022', '49258', '41453', '44057', '42475', '28737', '8983', '10827', '47075', '40395', '31879', '42767', '37961', '43954', '47633', '32547', '38130', '272662', '37213', '8702', '44876', '41890', '272970', '49760', '19643', '28186', '32894', '49622', '39639', '44239', '29285', '8493', '44306', '13755', '25006', '2121', '6466', '272977', '273338', '272665', '48931', '7679', '10301', '47497', '272886', '29473', '47694', '38975', '15008', '49918', '37642', '11383', '48872', '22268', '49539', '5276', '14494', '15230', '43461', '42794', '24056', '45581', '5138', '46600', '32751', '45151', '39342', '42910', '30229', '44519', '31627', '49526', '44414', '30474', '41893', '3963', '30789', '917959', '48158', '43489', '49614', '274301', '42670', '23283', '8428', '272831', '272614', '5094', '32695', '44580', '28601', '11439', '28046', '345493', '1202', '274290', '34569', '43465', '37287', '47696', '43071', '43929', '37465', '3709', '30437', '7629', '46254', '40759', '29999', '44963', '24253', '47798', '915595', '3386', '272950', '40147', '32266', '45221', '49577', '33008', '512', '29204', '541', '47337', '39025', '37876', '39061', '38979', '29779', '13248', '46951', '25943', '45079', '45425', '30749', '43015', '45955', '3413', '21681', '33524', '36016', '46677', '44237', '27040', '4952', '14836', '10', '21875', '42142', '37944', '38642', '41489', '44274', '28174', '46351', '11947', '42223', '888', '19909', '43193', '30725', '11280', '274143', '42850', '32020', '20273', '32760', '43753', '32725', '39178', '902242', '37858', '30579', '273048', '352221', '10728', '273069', '13986', '274294', '32312', '29716', '38313', '918529', '24801', '10389', '45152', '272656', '48539', '15138', '15004', '37833', '26933', '42888', '37571', '22970', '46679', '46423', '39185', '18850', '45612', '30415', '792', '16531', '31159', '43212', '41797', '44139', '22470', '32592', '13118', '11277', '41746', '15737', '40683', '39723', '272606', '11434', '40426', '42218', '30624', '48144', '38393', '1257', '240', '48509', '6575', '46613', '48142', '25311', '13888', '914876', '5054', '26691', '45899', '12602', '37774', '40475', '37646', '2994', '40923', '45801', '42564', '29078', '32768', '3962', '32856', '3523', '24316', '38402', '48696', '37471', '37258', '19833', '15131', '3619', '45979', '49382', '48243', '2404', '46869', '41345', '14626', '4699', '20265', '39074', '45996', '44653', '28040', '46971', '38760', '7693', '272945', '43898', '606', '45551', '44083', '49160', '23329', '48649', '8373', '8018', '3798', '7964', '44679', '1956', '273252', '46092', '4311', '43205', '47009', '48792', '38316', '272702', '35507', '273117', '273103', '49418', '7716', '7793', '43134', '9096', '49623', '38540', '43011', '41528', '16600', '41187', '45511', '4595', '40989', '39525', '38473', '14471', '45558', '1002', '38426', '46735', '10189', '272956', '33804', '39245', '917900', '31762', '44651', '37541', '38920', '16586', '41339', '43813', '18737', '4871', '29903', '25062', '44874', '31461', '38801', '39425', '799', '9119', '38888', '43390', '27936', '12463', '42088', '2274', '3784', '44411', '27225', '272673', '18191', '38170', '6715', '6698', '29126', '21566', '49754', '37214', '33002', '471', '913138', '44953', '11787', '15283', '22467', '39276', '30601', '15086', '4673', '15175', '29082', '27422', '16798', '38919', '44222', '42488', '35303', '34459', '1674', '47680', '47717', '49571', '35925', '11613', '37581', '45824', '30434', '11489', '15896', '46240', '520', '41556', '37836', '23915', '40574', '12726', '47822', '46450', '273235', '918252', '30800', '49558', '42396', '227', '30196', '49686', '11969', '32262', '30079', '11847', '12590', '47988', '49878', '39169', '39582', '39786', '2928', '45344', '41666', '12001', '26329', '45377', '43017', '902', '342', '13553', '38596', '39237', '37658', '44658', '21719', '12954', '37941', '44747', '42645', '43946', '32244', '27830', '43582', '46628', '30827', '45619', '32893', '38208', '41062', '37476', '44197', '32614', '49360', '42644', '47772', '37866', '11808', '15387', '18847', '27189', '19666', '44754', '9708', '49176', '14163', '37508', '43253', '26749', '41021', '39192', '269347', '31659', '29144', '39569', '49483', '32562', '42130', '14594', '38348', '26892', '7741', '49814', '48860', '43216', '30886', '40062', '16466', '32180', '272572', '26552', '45266', '48824', '14547', '32323', '41108', '49042', '45844', '7522', '45392', '37629', '27148', '35520', '49812', '6522', '2951', '272872', '24903', '28281', '26512', '4506', '39092', '42594', '12750', '41165', '14402', '28042', '44093', '42782', '24327', '290', '9861', '11188', '40866', '42804', '7271', '9074', '28355', '40636', '30315', '37612', '45704', '925277', '22793', '49481', '3891', '48281', '42786', '48211', '3737', '47246', '22644', '41913', '41579', '4439', '11448', '47756', '273244', '20719', '37899', '46812', '1400', '14388', '38802', '32560', '41521', '49582', '16831', '12109', '1043', '24878', '33267', '21718', '29837', '44570', '33246', '226', '42310', '14144', '27351', '30851', '3855', '43180', '41796', '5579', '45816', '11107', '37975', '28395', '10652', '36885', '14798', '48816', '7327', '49254', '13002', '24551', '43191', '294', '44391', '30629', '41081', '47961', '1884', '33860', '15039', '1212526', '17621', '48255', '35572', '22337', '49469', '41224', '42469', '4432', '40661', '42799', '45293', '274109', '39101', '8896', '272855', '49457', '48577', '31920', '16215', '31471', '48650', '41275', '47128', '4448', '48469', '41024', '35692', '4053', '48345', '39713', '38048', '48173', '30446', '43492', '40994', '38067', '42887', '31736', '912437', '38864', '42915', '3272', '45271', '43389', '45208', '30887', '18134', '10315', '30642', '33660', '42156', '32407', '25651', '22494', '28019', '49000', '40485', '869', '32580', '9804', '40002', '365', '40356', '49052', '37316', '46072', '8481', '3382', '47506', '42507', '273121', '7864', '39664', '41019', '31308', '37749', '45604', '23342', '3856', '49499', '22569', '1307', '44228', '3813', '269341', '39202', '9172', '39032', '39531', '41902', '13630', '37798', '46026', '2029', '30788', '30738', '39158', '12877', '23461', '46880', '49310', '32607', '39288', '27077', '46804', '26863', '761', '21641', '38192', '33678', '49387', '43400', '36762', '15375', '13243', '16631', '3867', '47563', '10636', '13070', '45705', '47479', '41449', '45380', '44491', '13122', '23460', '43153', '46709', '45697', '21005', '29707', '46685', '46810', '38687', '43456', '38875', '5057', '38268', '38274', '31544', '10619', '39080', '41703', '17565', '40215', '45234', '10897', '47452', '41230', '39649', '11057', '30191', '39815', '14267', '11131', '6068', '272698', '914797', '34315', '47816', '27188', '22474', '43293', '45636', '38956', '44469', '30250', '22889', '41682', '10561', '41202', '914950', '30701', '46848', '303908', '49850', '272839', '43321', '11728', '46308', '28156', '46566', '42003', '33526', '35165', '33034', '47184', '49177', '158', '27279', '48861', '23842', '6236', '37234', '15814', '39671', '273239', '37992', '42913', '659', '49073', '36986', '574719', '46070', '16830', '33421', '42749', '13692', '33666', '47758', '31894', '37335', '28591', '272871', '4438', '21903', '31898', '39305', '38066', '274327', '48598', '44739', '10023', '22370', '10889', '812', '48155', '30652', '42371', '39193', '3787', '39354', '14907', '32302', '16994', '29632', '44044', '43683', '9589', '41488', '24293', '42323', '42409', '47995', '11688', '49341', '28987', '10961', '44388', '45550', '40797', '46977', '29626', '27038', '44829', '13670', '1197668', '1201', '46717', '47384', '30420', '41751', '19002', '47122', '40682', '43491', '45419', '10535', '47841', '45601', '272792', '46282', '38946', '48985', '47241', '19720', '9176', '37525', '9185', '28970', '47395', '41905', '46981', '37217', '42753', '42687', '45285', '46013', '38045', '48087', '46077', '12914', '46391', '30388', '48880', '48908', '16238', '30419', '49007', '49912', '44390', '45646', '39289', '21385', '25339', '42536', '43308', '26822', '24226', '40360', '32490', '46883', '38605', '2979', '43809', '273232', '2905', '44459', '274268', '272668', '19702', '41459', '47423', '45058', '36377', '731379', '42795', '41269', '910994', '10292', '13290', '45114', '10513', '32974', '40362', '42829', '42344', '3789', '25953', '36569', '20222', '46300', '25894', '46799', '37608', '49934', '38128', '3348', '32500', '47992', '35889', '38222', '48058', '41025', '48148', '39173', '3338', '40952', '25547', '44951', '3329', '42595', '14209', '48838', '41799', '358706', '23691', '15610', '39706', '45811', '46806', '13038', '47295', '44008', '44480', '45093', '14896', '36455', '28995', '39026', '36752', '22908', '271573', '21702', '37762', '42512', '272719', '11510', '31914', '272908', '44037', '49815', '49049', '48229', '18746', '18344', '42151', '45437', '3678', '4518', '7653', '40219', '21527', '36233', '3542', '13559', '4749', '48164', '18342', '49372', '22297', '3489', '11321', '46012', '623', '341264', '11945', '39469', '17068', '21551', '47982', '32155', '40440', '9695', '44173', '10486', '31825', '12763', '930', '47974', '26886', '16817', '5331', '49565', '3221', '45451', '41004', '31409', '33662', '46800', '273043', '3179', '4459', '35678', '30868', '33688', '42790', '36031', '4982', '9629', '41554', '46016', '44090', '48550', '6546', '25126', '39714', '272691', '273094', '902400', '47480', '38600', '11852', '5584', '5046', '14351', '47472', '32532', '11547', '23023', '34757', '35558', '39474', '22455', '7260', '464', '45633', '41061', '9051', '49171', '13178', '29119', '32492', '10524', '45446', '38820', '10557', '43336', '349', '47146', '46313', '12293', '39564', '41692', '2711', '41178', '10936', '272596', '7946', '37487', '30781', '272695', '13704', '272638', '43322', '46040', '2428', '35930', '33681', '48319', '15168', '41064', '41207', '46939', '1176', '29128', '9707', '1081', '42253', '45281', '269325', '37306', '38468', '1035', '29713', '715', '274248', '37739', '15743', '41380', '44627', '450', '45407', '47615', '49775', '9986', '45242', '49979', '42209', '44495', '48494', '41761', '43444', '43455', '32398', '10019', '274090', '41664', '47168', '40625', '41128', '273010', '41464', '7958', '47789', '272604', '310', '48794', '36967', '44303', '3880', '995', '21679', '41399', '38625', '41498', '2270', '32352', '15453', '14673', '12043', '40374', '8637', '9368', '11727', '3690', '4743', '43137', '45100', '32059', '49293', '47805', '694', '11019', '44873', '2367', '47742', '44780', '12491', '43665', '3642', '29718', '35734', '40768', '38916', '34699', '47893', '30556', '47007', '47883', '35555', '46884', '31289', '38155', '7313', '27388', '47070', '3539', '442', '35524', '41866', '39618', '25638', '1384467', '46188', '42453', '49522', '272544', '12243', '911945', '939674', '13683', '33486', '32350', '45845', '15741', '274269', '47063', '28081', '35212', '5355', '32892', '30126', '48430', '43574', '34649', '44999', '48793', '2422', '42766', '14091', '6711', '18757', '12417', '44703', '31957', '39705', '45711', '47135', '44758', '32275', '22102', '43725', '37454', '48107', '666', '43766', '16814', '272661', '272689', '44120', '46158', '21644', '41031', '42132', '44642', '48845', '13164', '23819', '42735', '305616', '19114', '30395', '44626', '1023', '49149', '48726', '644', '42494', '28741', '28119', '49505', '45373', '42728', '47924', '12399', '46941', '48156', '39319', '11110', '4451', '27287', '44116', '44379', '38330', '12666', '48827', '13502', '1856', '42126', '45631', '47796', '49764', '46798', '35254', '44081', '32742', '45881', '11317', '2501', '3441', '45664', '45054', '22708', '10799', '45988', '41392', '39360', '37911', '4447', '26889', '15754', '7869', '43024', '42580', '1915', '37654', '47673', '48240', '47101', '47627', '43354', '49888', '43876', '39024', '37050', '14761', '25181', '47638', '49367', '7308', '24941', '42058', '42457', '9148', '47964', '5671', '33027', '39110', '49357', '44169', '47645', '38283', '272748', '23389', '22399', '272898', '1022', '40081', '46190', '38256', '47287', '813', '36185', '41412', '48259', '6925', '37794', '42559', '44748', '45126', '37363', '5045', '354', '36071', '36409', '29358', '40380', '9806', '8902', '34038', '13479', '45620', '38776', '29539', '40646', '27657', '49169', '3974', '22860', '10577', '48859', '41765', '46373', '5336', '26230', '32982', '11530', '41655', '37572', '12026', '885', '32711', '35974', '46952', '47619', '31468', '5148', '273111', '5956', '43351', '38575', '43130', '47540', '44915', '3421', '48110', '43171', '3394', '37578', '102066', '45694', '179', '272630', '2914', '48242', '45205', '42939', '38072', '37598', '48016', '47621', '39733', '26163', '274207', '918', '10611', '49782', '15485', '6679', '39171', '47268', '19543', '15742', '18879', '39501', '33302', '3172', '48046', '4055', '45554', '30374', '12115', '988', '272590', '12009', '38520', '38162', '31890', '35648', '29266', '33175', '37776', '272642', '25688', '1748', '39593', '10149', '8969', '49263', '36977', '48377', '6589', '46437', '46586', '19059', '30698', '49556', '45068', '41455', '10264', '45284', '10707', '41323', '49390', '34483', '43169', '47290', '37318', '37418', '24559', '49384', '28214', '47825', '40687', '25220', '42973', '44347', '47754', '39699', '38361', '44513', '39455', '37253', '1620519', '45761', '45753', '43501', '28251', '37148', '37694', '48783', '43998', '39623', '43735', '42031', '22847', '48480', '32085', '27398', '8434', '24870', '45035', '46410', '39650', '31540', '25127', '43851', '20928', '48560', '34107', '26787', '49065', '38872', '14537', '37224', '46269', '32154', '32107', '36490', '42692', '44794', '39115', '48580', '49440', '26836', '43670', '16847', '23721', '43482', '48707', '31976', '39335', '4083', '30048', '272621', '3324', '10083', '1879', '43576', '31397', '42616', '45196', '35465', '11452', '11212', '42198', '39308', '9654', '4010', '803', '39361', '38466', '45841', '16886', '31998', '6167', '40976', '47120', '39606', '10672', '42533', '34965', '49542', '44633', '30679', '41802', '31610', '39206', '44531', '6295', '41964', '10253', '42539', '5032', '30628', '46870', '39888', '43694', '13172', '9527', '602', '37562', '787', '44021', '273200', '32083', '48706', '47586', '11450', '39376', '3163', '42745', '19639', '1969', '186', '44952', '37777', '44172', '44877', '37398', '9600', '31148', '48239', '45681', '45821', '45794', '38627', '42282', '10519', '45337', '273241', '1700', '3716', '44947', '9854', '49428', '26479', '37239', '31445', '47012', '42468', '22750', '12961', '47749', '18543', '9420', '43041', '773', '30393', '38715', '18', '25329', '11299', '47562', '274117', '41334', '40577', '1005', '2504', '45170', '36786', '44522', '1179', '41174', '6649', '42269', '273202', '42412', '39494', '45347', '2370', '24356', '45522', '10804', '40367', '43591', '701', '38827', '38105', '272647', '9031', '41072', '29893', '274093', '24263', '16844', '26714', '3392', '4287', '48404', '41341', '4839', '48862', '43592', '31233', '45580', '272633', '44727', '15270', '42702', '22485', '5892', '39709', '798', '45892', '40689', '39337', '32286', '45573', '33005', '41201', '13652', '48488', '38984', '364884', '46772', '601', '4458', '41544', '30187', '14079', '41282', '3869', '40430', '23697', '38562', '45046', '32162', '45717', '1983', '48636', '161', '32969', '44941', '46697', '3478', '41819', '9824', '25762', '269342', '9262', '48284', '2127', '8080', '17041', '11037', '46871', '1384468', '43811', '272821', '35895', '44875', '7176', '49067', '44171', '31745', '46767', '42706', '49873', '40010', '40617', '38601', '252', '31587', '39330', '14632', '41365', '49119', '40965', '37120', '22248', '517', '38248', '47572', '44711', '34745', '49710', '28250', '29701', '48826', '42009', '45702', '45679', '25955', '26909', '272961', '42518', '28717', '46792', '11239', '35814', '46210', '45418', '10665', '37917', '45991', '30739', '38854', '23009', '46723', '47708', '46584', '38284', '13934', '43243', '3363', '19630', '34827', '33141', '8033', '41696', '40517', '9960', '15019', '33765', '42929', '45675', '41991', '304456', '16246', '10003', '39213', '40431', '26953', '27381', '43306', '24482', '38470', '48724', '49206', '43178', '42542', '38014', '40679', '32449', '6190', '49212', '49674', '41008', '38215', '14318', '42558', '45460', '43504', '13473', '41827', '39595', '12039', '41515', '16902', '47913', '42970', '46681', '10370', '49543', '9758', '439', '44035', '11440', '38772', '37230', '1227666', '13323', '47466', '45829', '43037', '43312', '30435', '14021', '40814', '10689', '45349', '46519', '37282', '49185', '32327', '20665', '27364', '38491', '790', '20278', '49159', '39119', '37025', '45258', '35489', '22707', '3165', '1212442', '11247', '45237', '44046', '29696', '5272', '9798', '38998', '273295', '33079', '27308', '42537', '43613', '10573', '37308', '44927', '27307', '49919', '32920', '40937', '13417', '4085', '11897', '43800', '44024', '15264', '43356', '42387', '25099', '48207', '42224', '11018', '46724', '49977', '37512', '17005', '34207', '45357', '41731', '30588', '43815', '19719', '45814', '272781', '45188', '49333', '21809', '47107', '37203', '12348', '43042', '10816', '47542', '12257', '46926', '1885', '45413', '45593', '37028', '47551', '4392', '20274', '48254', '47714', '39575', '31463', '48996', '40757', '40458', '13508', '9357', '43977', '34842', '30602', '39930', '46696', '14582', '12552', '3739', '47250', '45031', '1250034', '43588', '18950', '272878', '43005', '43513', '23840', '35435', '25244', '37365', '22654', '44134', '31406', '39472', '21846', '37524', '49407', '38385', '45404', '39767', '38869', '13474', '42832', '41980', '33889', '273213', '47061', '273215

In [7]:
comb_graph = dgl.batch([graphs[str(x)] for x in sorted_keys])
#nx.draw(dgl.to_networkx(graphs['21']), with_labels=True)

In [126]:
n_df.tail()

,atomic_number,radius,mass,electronegativity,hybridisation,ele__B,ele__BR,ele__C,ele__CL,ele__F,...,nei_OP,nei_OS,nei_OSS,nei_P,nei_PP,nei_PS,nei_S,nei_SS,nei_SSS,nei_SSSS
445074,8,60,16.00,3.44,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
445075,1,25,1.01,2.20,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
445076,6,70,12.00,2.55,4,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
445077,1,25,1.01,2.20,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
445078,1,25,1.01,2.20,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [86]:
save_obj_2_file(n_df, 'node_mean_dataframe.pickle')
save_obj_2_file(e_df, 'edge_mean_dataframe.pickle')
save_obj_2_file(comb_graph, 'combine_graph_mean_dataframe.pickle')

In [87]:
class GraphConv(tnn.Module):
    def __init__(self, in_feats, hid_feats, out_feats):
        super().__init__()
        self.conv1 = nn.SAGEConv(in_feats=in_feats, out_feats=hid_feats, bias=True, aggregator_type='mean')
        self.conv3 = nn.SAGEConv(in_feats=hid_feats, out_feats=out_feats, bias=True, aggregator_type='mean')
        
    def message_passing(self, g):

        g.update_all(fn.copy_e('e', 'm_e'), fn.sum('m_e', 'h_e'))
        g.update_all(fn.copy_u('h', 'm_n'), fn.sum('m_n', 'h_n'))
        g.ndata['h'] = torch.cat((g.ndata.pop('h_n'), g.ndata.pop('h_e')), 1)
        g.update_all(fn.copy_e('e', 'm_e'), fn.sum('m_e', 'h_e'))
        g.update_all(fn.copy_u('h', 'm_n'), fn.sum('m_n', 'h_n'))
        g.ndata['h'] = torch.cat((g.ndata.pop('h_n'), g.ndata.pop('h_e')), 1)
    
    def forward(self, graph, inputs):
        self.message_passing(graph)
        
        h = self.conv1(graph, inputs)
        h = F.relu(h)
        h = self.conv3(graph, h)
        with graph.local_scope():
            graph.ndata['h'] = h
            graph.apply_edges(fn.u_dot_v('h', 'h', 'score'))
            return graph.edata['score']

In [8]:
e_star = e_df.drop(2, axis=1)
norm_e = MinMaxScaler().fit(e_star)
norm_e_star = norm_e.transform(e_star)

In [111]:
save_obj_2_file(norm, 'norm_n.pickle')
save_obj_2_file(norm_e, 'norm_e.pickle')

In [13]:
comb_graph.ndata['h'] = torch.from_numpy(norm_n_df.astype('float32'))
comb_graph.edata['e'] = torch.from_numpy(norm_e_star.astype('float32'))
comb_graph.edata['score'] = torch.from_numpy(e_df[2].to_numpy().astype('float32'))
save_obj_2_file(comb_graph, 'combine_graph_mean.pickle')

In [15]:
dgl.distributed.partition_graph(comb_graph, "atb", 5, "atb_parted", part_method="random")

Converting to homogeneous graph takes 0.013s, peak mem: 12.453 GB
Reshuffle nodes and edges: 0.039 seconds
Split the graph: 0.116 seconds
Construct subgraphs: 0.060 seconds
Splitting the graph into partitions takes 0.216s, peak mem: 12.453 GB
part 0 has 209804 nodes and 88673 are inside the partition
part 0 has 321236 edges and 178640 are inside the partition
part 1 has 211046 nodes and 89256 are inside the partition
part 1 has 323660 edges and 179979 are inside the partition
part 2 has 210558 nodes and 89141 are inside the partition
part 2 has 322304 edges and 179199 are inside the partition
part 3 has 210979 nodes and 89317 are inside the partition
part 3 has 323318 edges and 179721 are inside the partition
part 4 has 210118 nodes and 88692 are inside the partition
part 4 has 321740 edges and 178769 are inside the partition
Save partitions: 0.563 seconds, peak memory: 12.453 GB
There are 896308 edges in the graph and 0 edge cuts for 5 partitions.

In [17]:
train_sp, val_sp, test_sp = random_split(norm_e_star, [0.5, 0.25, 0.25])
train_bin_full, train_bin, val_bin, test_bin = (np.zeros(len(comb_graph.edata['e'])) for i in range(4))
for x in train_sp.indices:
    train_bin[x] = 1
for y in val_sp.indices:
    val_bin[y] = 1
for z in test_sp.indices:
    test_bin[z] =1

for x in range(len(train_bin_full)):
    train_bin_full[x] = 1
print(train_bin_full)
print(train_bin)

[1. 1. 1. ... 1. 1. 1.]
[0. 1. 0. ... 1. 0. 0.]

In [18]:
comb_graph.edata['train_mask'] = torch.from_numpy(train_bin_full).bool()
comb_graph.edata['val_mask'] = torch.from_numpy(val_bin).bool()
comb_graph.edata['test_mask'] = torch.from_numpy(test_bin).bool()

In [21]:
dgl.distributed.partition_graph(comb_graph, "atb", 5, "atb_parted", part_method="random")

Converting to homogeneous graph takes 0.008s, peak mem: 12.453 GB
Reshuffle nodes and edges: 0.034 seconds
Split the graph: 0.114 seconds
Construct subgraphs: 0.045 seconds
Splitting the graph into partitions takes 0.193s, peak mem: 12.453 GB
part 0 has 210724 nodes and 89145 are inside the partition
part 0 has 322688 edges and 179336 are inside the partition
part 1 has 211303 nodes and 89311 are inside the partition
part 1 has 323850 edges and 179915 are inside the partition
part 2 has 209542 nodes and 88555 are inside the partition
part 2 has 320698 edges and 177927 are inside the partition
part 3 has 211193 nodes and 89253 are inside the partition
part 3 has 324000 edges and 180209 are inside the partition
part 4 has 210551 nodes and 88815 are inside the partition
part 4 has 322250 edges and 178921 are inside the partition
Save partitions: 0.568 seconds, peak memory: 12.453 GB
There are 896308 edges in the graph and 0 edge cuts for 5 partitions.

In [35]:
node_features = comb_graph.ndata['h']
edge_label = comb_graph.edata['score']
train_mask = comb_graph.edata['train_mask']

In [36]:
self_loop_g = dgl.add_self_loop(comb_graph)

In [37]:
model = GraphConv(self_loop_g.ndata['h'].shape[1], 20, 10)
optimizer = torch.optim.Adam(model.parameters())

In [90]:
device = torch.device('cuda:0')
model = model.to(device)
comb_graph = comb_graph.to(device)
edge_labels = edge_label.to(device)

In [91]:
import torch.distributed as dist
def init_process_group(world_size, rank):
    dist.init_process_group(
        backend='gloo',     # change to 'nccl' for multiple GPUs
        world_size=world_size,
        rank=rank)

In [92]:
from dgl.data import split_dataset
from dgl.dataloading import GraphDataLoader

def get_dataloaders(dataset, seed, batch_size=32):
    train_sp, val_sp, test_sp = split_dataset(dataset, frac_list=[0.8, 0.1, 0.1],
                                              shuffle=True, random_state=seed)
    train_loader = GraphDataLoader(train_set, use_ddp=True, batch_size=batch_size, shuffle=True)
    val_loader = GraphDataLoader(val_set, batch_size=batch_size)
    test_loader = GraphDataloader(test_set, batch_szie=batch_size)

    return train_loader,val_loader, test_loader

In [93]:
from torch.nn.parallel import DistributedDataParallel

def init_model(seed, model, device):
    torch.manual_seed(seed)
    model = model.to(device)
    if device.type == 'cpu':
        model = DistributedDataParallel(model)
    else:
        model = DistributedDataParallel(model, device_ids=[device], output_device=device)
        
    return model

In [94]:
def evaluate(model, dataloader, device):
    model.eval()

    total_loss = 0

    for bg, labels in dataloader:
        bg = bg.to(device)
        labels = labels.to(device)
        feats = bg.ndata.pop('h')
        with torch.no_grad():
            pred = model(bg, feats)
        total_loss += abs(pred[train_mask].flatten() - edge_label[train_mask]).mean()

    return total_loss

In [95]:
def save_model(epoch, model, optimizer, loss):
    epoch_str = str(epoch)
    torch.save({'epoch': epoch, 'model_state_dict': model.state_dict(), 
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': loss}, f'{epoch_str}_model_state.pt')

In [96]:
def main(rank, world_size, dataset, seed=0):
    init_process_group(word_size, rank)
    if torch.cuda.is_available():
        device = torch.device('cude:{:d}'.format(rank))
        torch.cuda.set_device(device)
    else:
        device = torch.device('cpu')

    model = init_model(seed, model, device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

    train_loader, val_loader, test_loader = get_dataloaders(dataset, seed)

    for epoch in range(1):
        model.train()
        train.loader.set_epoch(epoch)
        total_loss = 0
        for bg, labels in train_loader:
            bg = bg.to(device)
            labels = lables.to(device)
            feats = bg.ndata.pop('h')
            pred = model(bg, feats)

            loss = abs(pred.flatten() - labels).mean()
            total_loss += loss.cpu().item()
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()


        loss = total_loss
        print('Loss: {:.4f}'.format(loss))

        val_loss = evaluate(model, val_loader, device)
        print('Val loss: {:.4f}'.format(val_loss))
        if epoch%1000 == 0:
            save_model(epoch, model, optimizer, total_loss)
    test_loss = evaluate(model, test_loader, device)
    print('Test loss: {:.4f}'.format(test_loss))

In [97]:
j

RuntimeError: invalid device pointer: 0x7f2f53200000

In [28]:
optimizer.param_groups[0]['lr'] = 0.01

for epoch in range(10000):
        pred = model(comb_graph, node_features)
        loss = abs(pred[train_mask].flatten() - edge_label[train_mask]).mean()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(loss.item())

42317.3828125
45395.4375
42613.4375
43157.78125
44114.625
44018.8125
43267.140625
42486.421875
42561.48828125
43191.22265625
43311.27734375
42892.40234375
42422.12890625
42438.0625
42741.890625
42900.09765625
42818.875
42572.77734375
42360.515625
42431.36328125
42624.6796875
42663.41015625
42516.90625
42356.8203125
42381.03515625
42495.59375
42535.1015625
42465.45703125
42359.390625
42346.8671875
42427.640625
42456.68359375
42394.01171875
42329.4375
42356.20703125
42403.76171875
42396.4140625
42345.1328125
42326.14453125
42363.53125
42377.09375
42342.2421875
42321.6875
42345.1875
42357.0859375
42336.5078125
42319.28125
42334.43359375
42343.36328125
42325.84375
42318.265625
42330.84375
42331.66796875
42318.24609375
42318.7578125
42327.84765625
42321.7109375
42314.3125
42321.453125
42322.47265625
42313.9453125
42316.19140625
42319.91015625
42313.5078125
42313.328125
42316.36328125
42312.43359375
42312.0078125
42314.85546875
42311.38671875
42311.04296875
42312.83984375
42309.97265625
42310.65625
42310.97265625
42308.84765625
42310.33984375
42308.69921875
42308.99609375
42308.609375
42308.19140625
42308.51953125
42307.59375
42307.9296875
42307.24609375
42307.4609375
42306.78515625
42306.78515625
42306.8359375
42306.34375
42306.49609375
42305.71875
42306.015625
42305.5390625
42305.30859375
42305.609375
42304.92578125
42305.0625
42305.44140625
42304.48828125
42304.73828125
42304.796875
42304.06640625
42304.16796875
42304.47265625
42303.859375
42303.55859375
42303.6875
42303.96875
42303.37109375
42302.94921875
42302.8984375
42303.3359375
42303.39453125
42302.93359375
42302.37109375
42302.46875
42302.8125
42302.453125
42301.7734375
42301.6171875
42301.8984375
42302.0859375
42301.6640625
42301.12109375
42300.828125
42300.7109375
42300.59765625
42301.125
42301.73828125
42301.2421875
42300.2578125
42299.953125
42300.37890625
42301.015625
42300.140625
42299.33984375
42299.609375
42300.15625
42299.421875
42298.6796875
42298.42578125
42298.47265625
42299.12109375
42299.61328125
42298.671875
42297.9921875
42297.61328125
42297.66796875
42298.2109375
42298.71875
42298.19921875
42297.32421875
42296.83203125
42297.00390625
42297.13671875
42297.32421875
42297.29296875
42296.8203125
42296.45703125
42296.09765625
42296.078125
42296.484375
42296.95703125
42296.98046875
42295.9453125
42295.21484375
42295.578125
42296.2421875
42296.12109375
42295.3671875
42294.70703125
42294.2578125
42294.203125
42294.7265625
42296.15234375
42295.8359375
42294.6796875
42293.6171875
42293.4453125
42294.17578125
42294.87109375
42294.765625
42293.6015625
42292.8203125
42293.12890625
42294.48828125
42295.23046875
42293.6875
42292.44921875
42292.58984375
42293.36328125
42293.22265625
42292.73828125
42291.828125
42291.27734375
42291.33984375
42292.21484375
42293.25390625
42293.6953125
42291.97265625
42290.88671875
42290.734375
42291.39453125
42292.5859375
42292.43359375
42291.20703125
42290.10546875
42289.9609375
42290.74609375
42291.953125
42291.59375
42290.17578125
42289.3515625
42289.328125
42290.05859375
42291.38671875
42290.1015625
42288.89453125
42288.875
42290.2578125
42292.109375
42289.9765625
42288.34375
42289.00390625
42290.41015625
42289.01953125
42287.66796875
42288.17578125
42289.2109375
42288.54296875
42287.3515625
42286.8984375
42287.69140625
42288.70703125
42288.60546875
42287.3125
42286.2734375
42286.1328125
42287.32421875
42288.5546875
42287.4453125
42285.74609375
42285.078125
42285.63671875
42287.125
42287.37109375
42286.1953125
42284.7265625
42284.58984375
42286.06640625
42286.85546875
42285.6875
42284.140625
42283.31640625
42283.73046875
42285.09375
42285.82421875
42284.859375
42282.8671875
42282.73828125
42284.65234375
42284.21875
42282.95703125
42281.77734375
42281.54296875
42281.91015625
42282.4375
42283.06640625
42282.91015625
42281.890625
42280.71875
42280.1484375
42280.2578125
42281.1953125
42283.1015625
42283.55859375
42281.0703125
42279.3984375
42279.58984375
42280.89453125
42282.234375
42280.4921875
42278.5859375
42278.37109375
42281.09765625
42282.234375
42279.125
42277.828125
42280.3515625
42281.6484375
42278.6328125
42277.2421875
42278.08203125
42278.71484375
42277.91015625
42276.62890625
42276.4609375
42278.1796875
42280.34765625
42277.65234375
42275.9140625
42276.34765625
42277.83203125
42278.0859375
42276.69921875
42275.04296875
42274.59765625
42275.34375
42277.2109375
42277.85546875
42277.22265625
42274.8359375
42273.80859375
42274.9140625
42276.57421875
42276.77734375
42275.1796875
42273.40625
42273.1796875
42274.5234375
42276.484375
42275.03125
42273.0703125
42272.46875
42273.40625
42274.4453125
42274.15234375
42273.1875
42271.54296875
42270.93359375
42271.93359375
42273.72265625
42274.54296875
42272.41015625
42270.390625
42270.41015625
42274.28125
42277.50390625
42270.93359375
42270.765625
42275.2109375
42271.28125
42268.984375
42270.21875
42272.40234375
42271.875
42269.453125
42268.0703125
42268.95703125
42270.33984375
42270.8984375
42268.61328125
42267.3125
42268.9921875
42270.96875
42271.95703125
42268.703125
42266.7265625
42267.0390625
42268.8828125
42269.7265625
42267.18359375
42265.76171875
42266.33203125
42267.63671875
42268.80078125
42267.53125
42265.6171875
42264.6953125
42266.0859375
42268.75
42268.77734375
42266.62890625
42264.3125
42264.26953125
42266.1875
42266.8359375
42265.82421875
42263.828125
42262.86328125
42263.265625
42264.3828125
42266.86328125
42266.31640625
42264.35546875
42262.03125
42263.328125
42266.921875
42265.76953125
42262.8828125
42261.4375
42262.359375
42263.83984375
42264.69921875
42262.68359375
42261.14453125
42260.16796875
42259.9375
42261.07421875
42265.4375
42264.78515625
42262.58203125
42259.859375
42259.61328125
42261.4296875
42263.32421875
42262.79296875
42259.95703125
42258.76953125
42259.30859375

KeyboardInterrupt:

In [27]:
model.load_state_dict(torch.load('model_parms_42k.pt'))

In [48]:
(edge_label[train_mask])

tensor([180040.1094, 298029.2500, 268233.4688,  ..., 185079.9219,
        198301.7969, 123835.5703])

In [29]:
abs(pred[train_mask] - edge_label[train_mask]).mean()

tensor(80652.1484, grad_fn=<MeanBackward0>)

In [37]:
torch.save(model.state_dict(), 'model_parms_42k.pt')

In [ ]:
model = GraphConv(comb_graph.ndata['h'].shape[1], 50, 20, 10)
optimizer = torch.optim.Adam(model.parameters())

model_weave = WeavePredictor(comb_graph.ndata['h'].shape[1], comb_graph.edata['e'].shape[1],

In [42]:
print(norm_e_star)

[[0.37620873 0.20721817]
 [0.08499796 0.18207624]
 [0.0850565  0.18207624]
 ...
 [0.00174659 0.10583942]
 [0.08424243 0.17964315]
 [0.08451123 0.17680454]]